### ISSUE TITLE
Can not save local components

### ISSUE THREAD

**Issue by duboz** [vle-forge/irritator#104]
After opening QSS 1 SEIR system component and a new HSM component, I try to save same in mu local folder (~/.irritator-0.1/components/) but the "save" button stay inactivate.

**Comment by quesnel** [comment]
You need to copy the internal component before editing it. These
components are C++ code and can not be modified.

May be we can disable the edition of these components.

**Comment by quesnel** [comment]
And, in the file name area, you need to add the string `".irt"` to enable the save button.

There is surely a better thing to do. Do you have any ideas?

**Comment by duboz** [comment]
Maybe automatically complete the file name with the ".irt" extension if missing? Irritator users may ignore the type of extension to use.
