### ISSUE TITLE
irritator crashed

### ISSUE THREAD

**Issue by duboz** [vle-forge/irritator#15]
Right after launching irritator, adding a "flow" model in the editor window (right clic) cause a crash.

**Comment by quesnel** [comment]
Flow model produces output message at fixed time-step (1/default_samplerate parameter). Output values are double vectors but for now, GUI does not provide any way to fill this vector (input files for example). I will propose a solution quickly.

**Comment by duboz** [comment]
Great! Thank you.

**Comment by quesnel** [comment]
The `flow` model is replaced by `generator` with external sources. Will be removed soon.
