### ISSUE TITLE
Irritator crashes when opening a .irt file.

### ISSUE THREAD

**Issue by duboz** [vle-forge/irritator#16]
I built a SIR epidemiological model using the graphical interface. Everything looked good, I could simulate my model. I decided to save what I have done in a .irt file. I quit irritator and then try to reopen my file, but it crashed. I opened my .irt file to change the names of my models, suspecting that models with the same names (automatically generated by the GUI) could be the origin of the crash. Unfortunately changing the names does not fix the problem.
Hereafter are the two files I tried to open.
_--------
File 2:
--------_
8
0 qss2_i qss2_integrator 0.9 0.0001
1 qss2_m qss2_multiplier
2 qss2_i qss2_integrator 0.1 0.0001
3 qss2_w qss2_wsum_2 -0.1 0
4 qss2_w qss2_wsum_2 0.1 0
5 qss2_i qss2_integrator 0 0.0001
6 qss2_w qss2_wsum_2 -0.01 1
7 qss2_w qss2_wsum_2 0.01 0
0 0 3 1
0 0 1 1
1 0 4 0
1 0 3 0
2 0 7 0
2 0 6 0
2 0 4 1
2 0 1 0
3 0 0 0
4 0 6 1
5 0 7 1
6 0 2 0
7 0 5 0

_--------
File 2:
--------_
8
0 Suceptible qss2_integrator 0.9 0.0001
1 S_multi qss2_multiplier
2 Infectious qss2_integrator 0.1 0.0001
3 I_sum_1 qss2_wsum_2 -0.1 0
4 I_sum_2 qss2_wsum_2 0.1 0
5 Recovered qss2_integrator 0 0.0001
6 R_sum_1 qss2_wsum_2 -0.01 1
7 R_Sum_2 qss2_wsum_2 0.01 0
0 0 3 1
0 0 1 1
1 0 4 0
1 0 3 0
2 0 7 0
2 0 6 0
2 0 4 1
2 0 1 0
3 0 0 0
4 0 6 1
5 0 7 1
6 0 2 0
7 0 5 0

**Comment by quesnel** [comment]
I fix a problem last week when reading/writing files (commit 945b7d472190c4eb16dc87b837b7129630fb9742 branch test).
I merge test with master today. Can you update your Git repository and check your issue?

Attention: The irt files are not compatibles now (model's name removed). Sorry.

**Comment by duboz** [comment]
Thanks. I can save my models but they do not appear after reopening the file. No more crash anyway.

**Comment by quesnel** [comment]
I fix the reopening problem. See the test branch please.

**Comment by duboz** [comment]
OK tanks, it works on the test branch.
