### ISSUE TITLE
End of output files may come too early

### ISSUE THREAD

**Issue by ynedelec3** [vle-forge/irritator#29]
Hi,
with the following irt file :

> 4
> 0 qss1_integrator 0 0.01
> 1 qss1_integrator 1 0.01
> 2 qss1_multiplier
> 3 constant -1
> 0 0 1 0
> 1 0 2 0
> 2 0 0 0
> 3 0 2 1

and a simulation duration of 40.
output files end with incomplete data (observed value is missing, sometimes there is just ",-" as second data) :

> 39.39542200587955,-0.12
> 39.403486522008585,-0.13
> 39.41155103813762,-0.14
> 39.41961555426665,-0.15
> 39.42768007 

and 

> 39.322841360718265,-1.2478225
> 39.3309058768473,-1.2475806
> 39.33897039297633,-1.2472581
> 39.34703490910536,-1.2468548
> 39.35509942523439,-1.2463709
> 39.363163941363

when run should end at 40.0

0. dat and 1.dat read as follow when both value are 0.001 :

> 39.99365467195294,-0.76860154
> 39.994954484185236,-0.7678392
> 39.99625576205632,-0.76707226
> 39.99755851445617,-0.7663007
> 39.998862750304426,-0.76552445
> 39.99998064193025,-0.7642376

and 

> 39.994954484185236,-0.6796578
> 39.99625576205632,-0.6805243
> 39.99755851445617,-0.6813941
> 39.998862750304426,-0.68226725
> 39.99998064193025,-0.68371147

**Comment by ynedelec3** [comment]
Something strange happens :
with this irt file if plot output is selected, a run ends with incomplete file (last chars are ",-0.".
If plot option is then selected for the same output the end of file is immediately added (during selection, not necessary to launch a run). End of file seems to be waiting for some lost commit.

**Comment by ynedelec3** [comment]
During a simulation run all values are written in file object by instruction

`fmt::print(output->ofs, "{},{}\n", t, value);`

in function `observation_file_output_observe` (simulation-ediitor.cpp)

but the disk file is only partially updated meanwhile.

observation_file_output_free (file or plot_output.free) seems to be called only during output selection, which may delay the file completion...

**Comment by ynedelec3** [comment]
Final update of file occurs just when clicking on plot button but before reaching the
`plot_output& tf = plot_outs.alloc(names[i].c_str());` instruction in (node-ditor.cpp) :
`                ImGui::RadioButton("none", &choose, 0);
                ImGui::SameLine();
                ImGui::RadioButton("plot", &choose, 1);
                ImGui::SameLine();
                ImGui::RadioButton("file", &choose, 2);

                if (choose == 1) {
                    if (file) {
                        file_outs.free(*file);
                        sim.observers.free(mdl->obs_id);
                    }

                    if (!plot) {
                        plot_output& tf = plot_outs.alloc(names[i].c_str());
                        plot = &tf;
...`

**Comment by quesnel** [comment]
Hi,
In commit 81cb9da18ed5bbdd17a7e078bb3dbf36aa55b104, I tried to fix the problem. Can you test the `test` branch ?

**Comment by ynedelec3** [comment]
It works fine -)
Great thanks

**Comment by quesnel** [comment]
Cool! Thanks for the report. I will merge the branches soon.
