### ISSUE TITLE
Flow and filter models : core dumped. 

### ISSUE THREAD

**Issue by duboz** [vle-forge/irritator#68]
Adding a flow or a filter model in the editor cause a core dumped.

- While adding a "filter" model, I got this from gdb:
Thread 1 "irritator-0.1" received signal SIGTRAP, Trace/breakpoint trap. 0x00005555555692e4 in irt::flow::initialize() ()
It seems it is a wrong function call.

- While adding a "flow" model, I got exactly the same message from gdb.

**Comment by quesnel** [comment]
Fix in master branch.
