### ISSUE TITLE
QSS1, 2 and 3 SEIR : crash

### ISSUE THREAD

**Issue by duboz** [vle-forge/irritator#71]
Selecting either QSS1 QSS2 or QSS3 SEIR model crashes irrotator after one left mouse click in the editor window.
In the three cases, a QSS2 power model is visible.

**Comment by ovese** [comment]
Hello Raphael, I have fixed the cause of the crash. Please kindly let Gauthier review and merge. thank you

**Comment by ovese** [comment]
Hello Raphael, Please can you get Gauthier to review and merge the correction and lastest commit to the SEIR model. It works well now The changes are the following:

    //auto& pow_n = sim.alloc<qss2_power>();
    auto& pow_n = sim.alloc<abstract_power<QssLevel>>();

**Comment by quesnel** [comment]
Fix in master branch.
