### ISSUE TITLE
crash: visualization does not work

### ISSUE THREAD

**Issue by duboz** [vle-forge/irritator#86]
Can not observe simulation results in output editor window.

Actions : Select lotka-volterra QSS2, check observation for X variable, import model in simulation tab -> crash

(gdb) bt
#0  0x00007ffff7a46a7c in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff79f2476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff79d87f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff79d871b in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff79e9e96 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x000055555568447c in irt::simulation_init_observation(irt::simulation_editor&, irt::tree_node&, irt::component&) ()
#6  0x0000555555684745 in irt::simulation_init_observation(irt::component_editor&, irt::simulation_editor&, irt::tree_node&) ()
#7  0x0000555555684b7c in irt::simulation_copy(irt::component_editor&, irt::simulation_editor&) ()
#8  0x000055555568500b in irt::simulation_copy_impl(void*) ()
#9  0x000055555556dbc1 in irt::worker::run() ()
#10 0x00005555555a25b9 in void std::__invoke_impl<void, void (irt::worker::*)() noexcept, irt::worker*>(std::__invoke_memfun_deref, void (irt::worker::*&&)() noexcept, irt::worker*&&) ()
#11 0x00005555555a2375 in std::__invoke_result<void (irt::worker::*)() noexcept, irt::worker*>::type std::__invoke<void (irt::worker::*)() noexcept, irt::worker*>(void (irt::worker::*&&)() noexcept, irt::worker*&&) ()
#12 0x00005555555a2273 in void std::thread::_Invoker<std::tuple<void (irt::worker::*)() noexcept, irt::worker*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>)
    ()
#13 0x00005555555a20f4 in std::thread::_Invoker<std::tuple<void (irt::worker::*)() noexcept, irt::worker*> >::operator()() ()
#14 0x00005555555a1c50 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (irt::worker::*)() noexcept, irt::worker*> > >::_M_run() ()
#15 0x00007ffff7dbd2c3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007ffff7a44b43 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#17 0x00007ffff7ad6a00 in ?? () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by duboz** [comment]
Update : I run "git submodule update --remote" to be sure my branch is updated. I recompile from scratch, but the same error remains.
Note: I do a root install (not secure I know ;).

**Comment by duboz** [comment]
I tried import lotka volterra model first in simulation tab, then check X and Y observation checkboxes and simulation runs. But when I select action "Plot line" or "Plot scatter" in output editor, irritator crashes. If I select "Plot Raw", simulation runs but nothing is displayed.

Here the bt from gdb, same for both "Plot line" or "Plot scatter":

**Comment by quesnel** [comment]
Fix in master branch.
