### ISSUE TITLE
Crash : can not import model into simulation tab.

### ISSUE THREAD

**Issue by duboz** [vle-forge/irritator#87]
Irritator crashes when I select QSS 2 lotka-volterra (right panel), then check observation boxes for X et Y (left panel), then select import model in the simulation tab.
Hereafter the back trace with gdb:

(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7a25537 in __GI_abort () at abort.c:79
#2  0x00007ffff7a2540f in __assert_fail_base (fmt=0x7ffff7b8e128 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555555791b3f "obs",
    file=0x5555557991e0 "/home/raph/vle/irritator/app/gui/simulation-component.cpp", line=269, function=<optimized out>) at assert.c:92
#3  0x00007ffff7a34662 in __GI___assert_fail (assertion=0x555555791b3f "obs", file=0x5555557991e0 "/home/raph/vle/irritator/app/gui/simulation-component.cpp",
    line=269, function=0x555555799368 "irt::status irt::simulation_init_observation(irt::simulation_editor&, irt::tree_node&, irt::component&)")
    at assert.c:101
#4  0x000055555566d64c in irt::simulation_init_observation(irt::simulation_editor&, irt::tree_node&, irt::component&) ()
#5  0x000055555566d8bc in irt::simulation_init_observation(irt::component_editor&, irt::simulation_editor&, irt::tree_node&) ()
#6  0x000055555566dcbe in irt::simulation_copy(irt::component_editor&, irt::simulation_editor&) ()
#7  0x000055555566e0f8 in irt::simulation_copy_impl(void*) ()
#8  0x000055555556c867 in irt::worker::run() ()
#9  0x000055555559bf65 in void std::__invoke_impl<void, void (irt::worker::*)() noexcept, irt::worker*>(std::__invoke_memfun_deref, void (irt::worker::*&&)() noexcept, irt::worker*&&) ()
#10 0x000055555559bd8d in std::__invoke_result<void (irt::worker::*)() noexcept, irt::worker*>::type std::__invoke<void (irt::worker::*)() noexcept, irt::worker*>(void (irt::worker::*&&)() noexcept, irt::worker*&&) ()
#11 0x000055555559bca3 in void std::thread::_Invoker<std::tuple<void (irt::worker::*)() noexcept, irt::worker*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) ()
#12 0x000055555559bb3c in std::thread::_Invoker<std::tuple<void (irt::worker::*)() noexcept, irt::worker*> >::operator()() ()
#13 0x000055555559b6b0 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (irt::worker::*)() noexcept, irt::worker*> > >::_M_run() ()
#14 0x00007ffff7df3ed0 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#15 0x00007ffff7f26ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#16 0x00007ffff7afddef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by quesnel** [comment]
Fix in master branch.
