### ISSUE TITLE
Crash when setting parameter value

### ISSUE THREAD

**Issue by duboz** [vle-forge/irritator#88]
Irritator crashes when I tried to change the "reset" parameter for a QSS2 integrator in the modelling tab.
Hereafter the gdb bt;
#0  0x00007ffff7a46a7c in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff79f2476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff79d87f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff79d871b in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff79e9e96 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x0000555555b835ba in ImGui::GetKeyData(int) ()
#6  0x0000555555b838ba in ImGui::IsKeyReleased(int) ()
#7  0x0000555555aa3410 in irt::show_modeling_widget(irt::settings_manager const&, irt::component_editor&, irt::tree_node&, irt::component&) ()
#8  0x0000555555aa3678 in irt::application::show_modeling_editor_widget() ()
#9  0x0000555555571328 in irt::application::show_main_as_tabbar(ImVec2, ImVec2, int, int, int) ()
#10 0x0000555555570e1a in irt::application_show_windows(irt::application&) ()
#11 0x0000555555571013 in irt::application::show() ()
#12 0x0000555555c2fce5 in main ()

**Comment by quesnel** [comment]
Can't repro this bug. Closing now. Feel free to reopen. Thanks.
